apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "updateservice.operator.openshift.io/v1",
          "kind": "UpdateService",
          "metadata": {
            "name": "sample"
          },
          "spec": {
            "replicas": 1
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-14T21:01:52Z"
    description: Creates and maintains an OpenShift Update Service instance
    kubernetes.io/description: "This OpenShift Update Service operator Deployment
      reconciles local UpdateServices into more fundamental Kubernetes\nand OpenShift
      resources like Cincinnati Deployments and Routes, and it reports the status
      of those components in \nthe UpdateService status.\n"
    operatorframework.io/suggested-namespace: openshift-update-service
    operators.operatorframework.io/builder: operator-sdk-v1.31.0-ocp
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: update-service-operator.v5.0.3-dev
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: UpdateService is the Schema for the updateservices API.
      displayName: Update Service
      kind: UpdateService
      name: updateservices.updateservice.operator.openshift.io
      resources:
      - kind: Service
        name: policy-engine-service
        version: v1
      specDescriptors:
      - description: graphDataImage is a container image that contains the UpdateService
          graph data.
        displayName: Graph Data Image
        path: graphDataImage
      - description: releases is the repository in which release images are tagged,
          such as quay.io/openshift-release-dev/ocp-release.
        displayName: Releases
        path: releases
      - description: replicas is the number of pods to run. When >=2, a PodDisruptionBudget
          will ensure that voluntary disruption leaves at least one Pod running at
          all times.
        displayName: Replicas
        path: replicas
      statusDescriptors:
      - description: Conditions describe the state of the UpdateService resource.
        displayName: Conditions
        path: conditions
      - description: "policyEngineURI is the external URI which exposes the policy
          engine.  Available paths from this URI include: \n * /api/upgrades_info/v1/graph,
          with the update graph recommendations. * /api/upgrades_info/graph, with
          the update graph recommendations, versioned by content-type (e.g. application/vnd.redhat.cincinnati.v1+json)."
        displayName: Policy Engine URI
        path: policyEngineURI
      version: v1
  description: |-
    # Use Case
    Running an Update Service instance in a cluster is appealing for offline OpenShift
    clusters or for admins that want to provide their own graph data instead of
    using [https://github.com/openshift/cincinnati-graph-data](https://github.com/openshift/cincinnati-graph-data/).

    # About Update Service
    Update Service uses **Cincinnati** which is an update protocol designed to facilitate
    automatic updates. It describes a particular method for representing transitions between
    releases of a project and allowing a client to perform automatic updates between these
    releases.

    ## Components
    A **Graph Builder** iterates over the release payloads hosted by the
    storage component and builds a DAG of the releases. It is responsible for
    verifying that the graph described by the releases is acyclic and connected.

    A **Policy Engine** is in charge of altering a client's view of the graph
    by applying a set of filters which are defined within the particular Policy
    Engine instance. Both the input to and the output from Policy Engines is a
    graph, allowing multiple Policy Engines to be chained together. The first
    Policy Engine in a chain will fetch its graph from the Graph Builder and the
    last Policy Engine in a chain will serve the modified graph to the client.

    An **Update Service client** is the end consumer of the release payloads. The
    client periodically queries the Policy Engine for updates and applys them if
    available.

    # Query OpenShift's Update Service Endpoint
    $ curl --silent --header 'Accept:application/json' 'https://api.openshift.com/api/upgrades_info/v1/graph?arch=amd64&channel=stable-4.2' | jq '. as $graph | $graph.nodes | map(.version == "4.2.13") | index(true) as $orig | $graph.edges | map(select(.[0] == $orig)[1]) | map($graph.nodes[.])'
  displayName: OpenShift Update Service
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - pods
          - secrets
          - services
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - images
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - updateservice.operator.openshift.io
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
        serviceAccountName: updateservice-operator
      deployments:
      - name: updateservice-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: updateservice-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: updateservice-operator
            spec:
              containers:
              - env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAME
                  value: updateservice-operator
                - name: RELATED_IMAGE_OPERAND
                  value: quay.io/cincinnati/cincinnati:latest
                image: controller:latest
                imagePullPolicy: Always
                name: updateservice-operator
                resources: {}
              serviceAccountName: updateservice-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - endpoints
          - events
          - persistentvolumeclaims
          - pods
          - secrets
          - services
          - services/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resourceNames:
          - updateservice-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - get
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - updateservice.operator.openshift.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: updateservice-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - Update Service
  - UpdateService
  - update-service
  - OSUS
  - Cincinnati
  - version
  - upgrade
  links:
  - name: Update Service Operator
    url: https://github.com/openshift/cincinnati-operator
  - name: OpenShift Update Service
    url: https://github.com/openshift/cincinnati
  - name: OpenShift Graph Data
    url: https://github.com/openshift/cincinnati-graph-data
  maintainers:
  - email: aos-team-ota@redhat.com
    name: OpenShift Update Service maintainers
  maturity: alpha
  provider:
    name: Red Hat
  relatedImages:
  - image: quay.io/cincinnati/cincinnati:latest
    name: operand
  version: 5.0.3-dev
